FROM node:20-alpine AS builder
WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM caddy:2-alpine
COPY --from=builder /frontend/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile
